language: ruby
sudo: false
rvm:
  - 2.1.2
cache: bundler
addons:
  apt:
    packages:
    - aspell
    - aspell-en
before_install:
  - export GOPATH=$HOME/gopath
before_script:
  - git fetch origin
  - git submodule update --init
script:
  - make links
  - bundle exec ruby ./tools/spellcheck/branch-spellcheck.rb $TRAVIS_BRANCH
  - ./compile.sh
branches:
  except:
    - master
notifications:
  email: false
